const coursesData = [
  {
    title: "The Complete Front-End Web Development Course!",
    description: "Get started as a front-end web developer...",
    teacher: "Joseph",
    rating: "4.4",
    duration: "17 hours",
    lectures: "126",
    "img-url": "https://img-c.udemycdn.com/course/240x135/1166306_84a1_3.jpg",
    level: "beginner",
    id: '1',
  },
  {
    title: "Front End Web Development Ultimate Course 2021",
    description: "You'll learn all fundamentals of front-end...",
    teacher: "Tech Plus",
    rating: "4.3",
    duration: "91.5 hours",
    lectures: "689",
    "img-url": "https://img-c.udemycdn.com/course/240x135/1691862_eba9_3.jpg",
    level: "beginner",
    id: '2',
  },
  {
    title: "The Complete Front End Web Development Bootcamp",
    description: "Learn HTML, HTML5, CSS, CSS3, JavaScript...",
    teacher: "Igneus",
    rating: "4.5",
    duration: "19 hours",
    lectures: "128",
    "img-url": "https://img-c.udemycdn.com/course/240x135/905850_68a2_5.jpg",
    level: "intermediate",
    id: '3',
  },
  {
    title: "Front End Web Development: Complete Guide",
    description: "Learn complete front end web development...",
    teacher: "Fatah",
    rating: "4.3",
    duration: "13.5 hours",
    lectures: "215",
    "img-url": "https://img-c.udemycdn.com/course/240x135/3442782_5f7f.jpg",
    level: "intermediate",
    id: '4',
  },
  {
    title: "Full Front-End Web Development Course",
    description: "Learn modern web development with HTML, CSS, Bootstrap...",
    teacher: "Oak Academy",
    rating: "4.8",
    duration: "15 hours",
    lectures: "123",
    "img-url": "https://img-c.udemycdn.com/course/240x135/3633728_3051_2.jpg",
    level: "advanced",
    id: '5',
  },
  {
    title: "Front End Web Developent Bootcamp: Twitter Clone",
    description: "Build a twitter clone using HTML, CSS...",
    teacher: "George",
    rating: "4.8",
    duration: "12.5 hours",
    lectures: "108",
    "img-url": "https://img-c.udemycdn.com/course/240x135/2394680_3d92_2.jpg",
    level: "advanced",
    id: '6',
  },
  {
    title: "Guide to Front-End Web Development and Design",
    description: "Complete guide to learning how to program...",
    teacher: "Laurence",
    rating: "4.4",
    duration: "17.5 hours",
    lectures: "215",
    "img-url": "https://img-c.udemycdn.com/course/240x135/797040_0cb8_4.jpg",
    level: "expert",
    id: '7',
  },
  {
    title: "Ultimate Web Designer & Developer course",
    description: "Become a full stack designer and learn...",
    teacher: "Brad",
    rating: "4.6",
    duration: "33 hours",
    lectures: "253",
    "img-url": "https://img-c.udemycdn.com/course/240x135/446134_383c_3.jpg",
    level: "expert",
    id: '8',
  },
];
export default coursesData;
